extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Random password for the MongoDB administrator. A new value is generated on each deployment.')
@secure()
param generatedPassword string = newGuid()

var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// MongoDB variables
//////////////////////////////////////////

var database = context.resource.properties.?database ?? 'mongo_db'
var username = 'admin'
// MongoDB 8.0 and later refuse to start on Linux kernel 6.19 and newer
// (https://jira.mongodb.org/browse/SERVER-121912), which recent cluster nodes
// already run. 7.0 starts on every kernel.
var tag string = '7.0'
var port = 27017
var host = '${resourceName}.${namespace}.svc.cluster.local'

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// MongoDB credentials
//
// The resource type has no credential properties, so the Recipe generates the
// administrator password itself and returns it inside `secrets.connectionString`.
// Store the credentials in a Kubernetes Secret so the MongoDB container reads
// them through secretKeyRef rather than carrying the password inline in the
// Pod spec.
//////////////////////////////////////////

resource dbSecret 'core/Secret@v1' = {
  metadata: {
    name: '${resourceName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    USERNAME: username
    PASSWORD: generatedPassword
  }
}

//////////////////////////////////////////
// MongoDB Deployment
//////////////////////////////////////////

resource mongo 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent database. Recreate ensures the old Pod is
    // torn down before the new one starts on update, so two divergent MongoDB
    // servers never serve the same Service at once (the default RollingUpdate
    // would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
        annotations: {
          // A new generated password changes the Pod template, so MongoDB
          // restarts on a fresh data volume and creates the administrator with
          // the password now in the Secret and the connection string.
          'radapp.io/generated-password-hash': uniqueString(generatedPassword)
        }
      }
      spec: {
        containers: [
          {
            // This container is the running MongoDB server. The image entrypoint
            // creates the administrator in the `admin` database from the
            // MONGO_INITDB_ROOT_* variables on first start and then enables
            // authentication. It prepends `mongod` when the first arg starts
            // with '-'. The WiredTiger cache is capped so the server stays well
            // within the memory request instead of sizing itself from the node.
            name: 'mongo'
            image: 'mongo:${tag}'
            args: [
              '--wiredTigerCacheSizeGB'
              '0.25'
            ]
            ports: [
              {
                name: 'mongodb'
                containerPort: port
              }
            ]
            env: [
              {
                name: 'MONGO_INITDB_ROOT_USERNAME'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'USERNAME'
                  }
                }
              }
              {
                name: 'MONGO_INITDB_ROOT_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'PASSWORD'
                  }
                }
              }
            ]
            // While the entrypoint creates the administrator, it runs a
            // temporary server bound to 127.0.0.1 only. The port on the Pod IP
            // opens only once the final server is up with authentication on.
            readinessProbe: {
              tcpSocket: {
                port: 'mongodb'
              }
              initialDelaySeconds: 5
              periodSeconds: 5
            }
            resources: {
              requests: {
                memory: '512Mi'
              }
            }
            volumeMounts: [
              {
                name: 'data'
                mountPath: '/data/db'
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'data'
            emptyDir: {}
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${dbSecret.metadata.namespace}/providers/core/Secret/${dbSecret.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${mongo.metadata.namespace}/providers/apps/Deployment/${mongo.metadata.name}'
  ]
  values: {
    endpoint: '${host}:${port}'
    database: database
  }
  secrets: {
    // The administrator is created in the `admin` database, so the connection
    // string sets `authSource=admin` and selects `database` as the default
    // database. Radius materializes it into the managed Radius.Security/secrets
    // resource; it is never written onto the resource.
    #disable-next-line outputs-should-not-contain-secrets
    connectionString: 'mongodb://${username}:${generatedPassword}@${host}:${port}/${database}?authSource=admin'
  }
}
