/*
Copyright 2025 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by gen-embed; DO NOT EDIT.

package resourcetypes

import "embed"

// DefaultManifests contains the embedded resource type manifests for default registration.
//
//go:embed defaults.yaml
//go:embed Compute/containers/containers.yaml
//go:embed Compute/persistentVolumes/persistentVolumes.yaml
//go:embed Compute/routes/routes.yaml
//go:embed Data/mySqlDatabases/mySqlDatabases.yaml
//go:embed Data/postgreSqlDatabases/postgreSqlDatabases.yaml
//go:embed Security/secrets/secrets.yaml
var DefaultManifests embed.FS
