extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// Redis variables
//////////////////////////////////////////

var sizeValue = context.resource.properties.?size ?? 'S'
var tag string = '7-alpine'
var port = 6379

// Unlike the database recipes (which take a developer-supplied password), the
// Radius.Data/redisCaches resource exposes no credential property — the platform
// provisions the access key. Bicep has no stateful RNG, so this recipe derives a
// stable password from the resource id via uniqueString(): deterministic and
// idempotent across redeploys. (The Terraform variant uses a random_password kept
// in state.) The value is stored in the Kubernetes Secret below.
var password = uniqueString(context.resource.id, 'redis-password')

// Each size maps to a memory request (pod scheduling) and a Redis `--maxmemory`
// budget (dataset cap). maxmemory is kept below the request so Redis evicts keys
// before the container is under memory pressure, rather than being OOM-killed.
var memory = {
  S: {
    memoryRequest: '256Mi'
    maxmemory: '200mb'
  }
  M: {
    memoryRequest: '512Mi'
    maxmemory: '400mb'
  }
  L: {
    memoryRequest: '1Gi'
    maxmemory: '800mb'
  }
}

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// Redis credentials
//
// The generated password is stored in a Kubernetes Secret so the Redis container
// references it via secretKeyRef rather than carrying it inline in the Pod spec.
//////////////////////////////////////////

resource redisSecret 'core/Secret@v1' = {
  metadata: {
    name: '${resourceName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    REDIS_PASSWORD: password
  }
}

//////////////////////////////////////////
// Redis Deployment
//////////////////////////////////////////

resource redis 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    // Redis here is a single-replica, non-persistent cache. Recreate ensures the
    // old Pod is torn down before the new one starts on update, so two divergent
    // Redis instances never serve the same Service at once (the default
    // RollingUpdate would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        containers: [
          {
            // This container is the running Redis instance. The default redis
            // image entrypoint prepends `redis-server` when the first arg starts
            // with '-', so `--requirepass $(REDIS_PASSWORD)` enables auth. The
            // $(REDIS_PASSWORD) token is substituted by Kubernetes from the env
            // var below (sourced from the Secret) — the password is never inlined.
            name: 'redis'
            image: 'redis:${tag}'
            args: [
              '--requirepass'
              '$(REDIS_PASSWORD)'
              '--maxmemory'
              memory[sizeValue].maxmemory
              '--maxmemory-policy'
              'allkeys-lru'
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            resources: {
              requests: {
                memory: memory[sizeValue].memoryRequest
              }
            }
            env: [
              {
                name: 'REDIS_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: redisSecret.metadata.name
                    key: 'REDIS_PASSWORD'
                  }
                }
              }
            ]
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

var host = '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${redisSecret.metadata.namespace}/providers/core/Secret/${redisSecret.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${redis.metadata.namespace}/providers/apps/Deployment/${redis.metadata.name}'
  ]
  values: {
    host: host
    port: port
  }
  secrets: {
    // In-cluster Redis is reached over plaintext (no TLS), so the scheme is
    // `redis://` (not `rediss://`). Radius materializes this into the managed
    // Radius.Security/secrets resource; it is never written onto the resource.
    url: 'redis://:${password}@${host}:${port}'
  }
}
