targetScope = 'resourceGroup'

//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the flexible server. Defaults to the current resource group location.')
param location string = resourceGroup().location

//////////////////////////////////////////
// MySQL variables
//////////////////////////////////////////

var username = context.resource.properties.username
var password = context.resource.properties.password
var database = context.resource.properties.?database ?? 'mysql_db'

// MySQL flexible server always listens on 3306. The AVM module this Recipe
// replaces declared no port output, so the value is stated here to keep the
// resource type's `port` contract populated on Azure.
var port = 3306

// Azure Database for MySQL flexible server offers 5.7 and 8.0. The resource
// type also allows 8.4, which has no flexible server equivalent, so it maps
// onto 8.0 exactly as the previous direct-module Recipe did.
var version = (context.resource.properties.?version ?? '8.4') == '5.7' ? '5.7' : '8.0.21'

@description('Compute SKU for the flexible server.')
param skuName string = 'Standard_B1ms'

@description('Compute tier for the flexible server.')
param tier string = 'Burstable'

@description('Provisioned storage for the flexible server, in GiB.')
param storageSizeGB int = 32

@description('Additional MySQL server parameters to apply, each of the shape { name, value }. require_secure_transport is owned by this Recipe and reported through sslMode, so it must not be set here.')
param serverConfigurations array = []

// Globally unique Azure names use a stable hash over the Radius resource ID and
// the target resource group, matching the naming the Azure Recipe Pack applied
// while this type referenced the AVM module directly.
var serverName = toLower('mysql-${take(uniqueString(context.resource.id, resourceGroup().id), 16)}')

// Azure tag names cannot contain '/', so the Radius labels use '-'. `application`
// is optional on this type, so it is reached with safe navigation: ARM resolves a
// plain property path before evaluating any fallback, and would fail the
// deployment outright if the key were absent.
var tags = {
  'radapp.io-resource': context.resource.name
  'radapp.io-application': context.?application.?name ?? ''
  'radapp.io-environment': context.?environment.?name ?? ''
  'radapp.io-resource-type': replace(context.resource.type, '/', '-')
}

//////////////////////////////////////////
// MySQL flexible server
//
// Azure Database for MySQL flexible server runs with
// require_secure_transport = ON. This Recipe deliberately keeps that default
// rather than weakening it to match the Kubernetes and AWS Recipes, and
// reports the requirement through the resource type's `sslMode` output so a
// connecting application can negotiate TLS instead of discovering the
// requirement from a failed handshake.
//////////////////////////////////////////

resource flexibleServer 'Microsoft.DBforMySQL/flexibleServers@2023-12-30' = {
  name: serverName
  location: location
  tags: tags
  sku: {
    name: skuName
    tier: tier
  }
  properties: {
    administratorLogin: username
    // Radius injects `password` decrypted from the resource's
    // x-radius-sensitive property, so the value is secret despite arriving
    // through the untyped `context` object the linter cannot see into.
    #disable-next-line use-secure-value-for-secure-inputs
    administratorLoginPassword: password
    version: version
    storage: {
      storageSizeGB: storageSizeGB
      autoGrow: 'Enabled'
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
  }
}

resource mysqlDatabase 'Microsoft.DBforMySQL/flexibleServers/databases@2023-12-30' = {
  parent: flexibleServer
  name: database
  properties: {
    charset: 'utf8mb4'
    collation: 'utf8mb4_general_ci'
  }
}

// Matches the connectivity the Azure Recipe Pack provided previously: the
// database has to be reachable from the application's cluster, which is not
// necessarily inside the server's virtual network.
resource allowAll 'Microsoft.DBforMySQL/flexibleServers/firewallRules@2023-12-30' = {
  parent: flexibleServer
  name: 'allow-all'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '255.255.255.255'
  }
}

// Applied one at a time because the server rejects concurrent configuration
// writes, and after the database so the two do not contend for the server.
@batchSize(1)
resource configurations 'Microsoft.DBforMySQL/flexibleServers/configurations@2023-12-30' = [
  for configuration in serverConfigurations: {
    parent: flexibleServer
    name: configuration.name
    properties: {
      source: 'user-override'
      value: configuration.value
    }
    dependsOn: [
      mysqlDatabase
      allowAll
    ]
  }
]

//////////////////////////////////////////
// Output
//////////////////////////////////////////

output result object = {
  resources: [
    flexibleServer.id
  ]
  values: {
    host: flexibleServer.properties.fullyQualifiedDomainName
    port: port
    database: database
    // Azure Database for MySQL flexible server requires TLS and this Recipe
    // does not override require_secure_transport.
    sslMode: 'required'
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    password: password
  }
}
