extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Random secret key for the object store. Generated on each deployment.')
@secure()
param generatedSecretKey string = newGuid()

var resourceName = context.resource.name
// A unique per-resource name so two objectStorage resources that share a display
// name (or the same name across recreates) never collide on their Kubernetes
// objects, including the volume that holds the data. The name is cut to 49
// characters so the Service name and label value stay within 63 characters.
var uniqueName = '${take(resourceName, 49)}-${uniqueString(context.resource.id)}'
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// Object storage variables
//////////////////////////////////////////

var containerName = context.resource.properties.?containerName ?? 'data'
var tag string = '1.0.0'
var port = 9000
var storageSize = '1Gi'
var host = '${uniqueName}.${namespace}.svc.cluster.local'
var endpoint = 'http://${host}:${port}'

// The access key ID is not sensitive. The secret key is generated by the Recipe
// and returned through Radius managed secrets.
var accessKey = 'radius'

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

// Pods and selectors also carry the unique name, so the Service never selects
// the Pods of another resource that has the same display name.
var selectorLabels = {
  'radapp.io/resource':         resourceName
  'app.kubernetes.io/instance': uniqueName
}

// Starts RustFS, then creates the bucket named by `containerName` through the
// S3 API on 127.0.0.1, signing the request with the root credentials. The
// readiness probe passes only once the bucket exists. SIGTERM is forwarded to
// the server so it shuts down cleanly.
var startScript = '''
set -u
if ! printf '%s' "$BUCKET_NAME" | grep -Eq '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$'; then
  echo "Invalid bucket name: $BUCKET_NAME" >&2
  exit 1
fi
/entrypoint.sh rustfs &
server=$!
trap 'kill -TERM "$server" 2>/dev/null' TERM INT
bucket() {
  curl -fsS -o /dev/null --aws-sigv4 'aws:amz:us-east-1:s3' --user "$RUSTFS_ACCESS_KEY:$RUSTFS_SECRET_KEY" "$@" "http://127.0.0.1:9000/$BUCKET_NAME"
}
until bucket -I 2>/dev/null || bucket -X PUT 2>/dev/null; do
  kill -0 "$server" 2>/dev/null || break
  sleep 2
done
wait "$server"
status=$?
while kill -0 "$server" 2>/dev/null; do
  wait "$server"
  status=$?
done
exit "$status"
'''

//////////////////////////////////////////
// Object storage credentials
//////////////////////////////////////////

resource credentials 'core/Secret@v1' = {
  metadata: {
    name: '${uniqueName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    accessKey: accessKey
    secretKey: generatedSecretKey
  }
}

//////////////////////////////////////////
// Object storage volume
//////////////////////////////////////////

resource data 'core/PersistentVolumeClaim@v1' = {
  metadata: {
    name: '${uniqueName}-data'
    namespace: namespace
    labels: labels
  }
  spec: {
    accessModes: [
      'ReadWriteOnce'
    ]
    resources: {
      requests: {
        storage: storageSize
      }
    }
  }
}

//////////////////////////////////////////
// Object storage Deployment
//////////////////////////////////////////

resource store 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica server on a ReadWriteOnce volume. Recreate ensures the
    // old Pod is torn down and releases the volume before the new one starts on
    // update (the default RollingUpdate would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: selectorLabels
    }
    template: {
      metadata: {
        labels: union(labels, selectorLabels)
        annotations: {
          // A new generated secret key changes the Pod template, so the server
          // restarts and reads the updated Secret during deployment.
          'radapp.io/generated-secret-key-hash': uniqueString(generatedSecretKey)
        }
      }
      spec: {
        // Service links would inject variables such as `RUSTFS_PORT` whenever a
        // Service named `rustfs` exists in the namespace.
        enableServiceLinks: false
        securityContext: {
          // The image runs as the `rustfs` user (UID and GID 10001). fsGroup
          // makes the volume writable for it on storage classes that support it.
          fsGroup: 10001
        }
        containers: [
          {
            // A single-node RustFS server, an S3-compatible object store, serving
            // the S3 API over HTTP on port 9000.
            name: 'rustfs'
            image: 'rustfs/rustfs:${tag}'
            command: [
              'sh'
              '-c'
              startScript
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'RUSTFS_ACCESS_KEY'
                valueFrom: {
                  secretKeyRef: {
                    name: credentials.metadata.name
                    key: 'accessKey'
                  }
                }
              }
              {
                name: 'RUSTFS_SECRET_KEY'
                valueFrom: {
                  secretKeyRef: {
                    name: credentials.metadata.name
                    key: 'secretKey'
                  }
                }
              }
              {
                name: 'RUSTFS_VOLUMES'
                value: '/data'
              }
              {
                name: 'RUSTFS_ADDRESS'
                value: ':${port}'
              }
              {
                // Serve only the S3 API; no web console.
                name: 'RUSTFS_CONSOLE_ENABLE'
                value: 'false'
              }
              {
                name: 'RUSTFS_CHECK_UPDATE'
                value: 'false'
              }
              {
                // Log to stdout instead of files under /logs.
                name: 'RUSTFS_OBS_LOG_DIRECTORY'
                value: ''
              }
              {
                name: 'BUCKET_NAME'
                value: containerName
              }
            ]
            readinessProbe: {
              exec: {
                command: [
                  'sh'
                  '-c'
                  'curl -fsS -o /dev/null -I --aws-sigv4 aws:amz:us-east-1:s3 --user "$RUSTFS_ACCESS_KEY:$RUSTFS_SECRET_KEY" "http://127.0.0.1:9000/$BUCKET_NAME"'
                ]
              }
              initialDelaySeconds: 2
              periodSeconds: 5
            }
            resources: {
              requests: {
                memory: '256Mi'
              }
            }
            volumeMounts: [
              {
                name: 'data'
                mountPath: '/data'
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'data'
            persistentVolumeClaim: {
              claimName: data.metadata.name
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: selectorLabels
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${credentials.metadata.namespace}/providers/core/Secret/${credentials.metadata.name}'
    '/planes/kubernetes/local/namespaces/${data.metadata.namespace}/providers/core/PersistentVolumeClaim/${data.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${store.metadata.namespace}/providers/apps/Deployment/${store.metadata.name}'
  ]
  values: {
    // The S3 endpoint. Clients use path-style requests (`<endpoint>/<bucket>`)
    // and any region name, for example `us-east-1`.
    endpoint: endpoint
    // The S3 access key ID, the counterpart of the Azure Storage account name.
    accountName: accessKey
  }
  secrets: {
    // The S3 secret access key, generated by the Recipe. Radius materializes it
    // into the managed Radius.Security/secrets resource; it is never written
    // onto the resource.
    accountKey: generatedSecretKey
    // The endpoint with the credentials embedded, `http://<accessKey>:<secretKey>@<host>:9000`.
    connectionString: 'http://${accessKey}:${generatedSecretKey}@${host}:${port}'
  }
}
