variable "context" {
  description = "Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.dev/operations/custom-recipes/"
  type        = any
}

variable "host_path" {
  description = "Host path for the persistent volume"
  type        = string
  default     = "/mnt/data"
}

variable "storage_class" {
  description = "StorageClass name to set on the PersistentVolume"
  type        = string
  default     = "manual"
}

variable "access_mode" {
  description = "Default access mode for the PersistentVolume"
  type        = string
  default     = "ReadWriteOnce"
}