variable "context" {
  description = "Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.dev/operations/custom-recipes/"
  type = object({
    resource = object({
      name = string
      properties = object({
        size = string
      })
    })
    runtime = object({
      kubernetes = object({
        namespace = string
      })
    })
    application = optional(object({
      name = string
    }))
  })
}

variable "host_path" {
  description = "Host path for the persistent volume"
  type        = string
  default     = "/mnt/data"
}