terraform {
  required_version = ">= 1.5"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.37.1"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.6.0"
    }
  }
}

locals {
  resource_name = var.context.resource.name
  # A unique per-resource name so two objectStorage resources that share a
  # display name (or the same name across recreates) never collide on their
  # Kubernetes objects, including the volume that holds the data. The name is
  # cut to 49 characters so the Service name and label value stay within 63.
  unique_name      = "${substr(var.context.resource.name, 0, 49)}-${substr(sha256(var.context.resource.id), 0, 13)}"
  application_name = var.context.application != null ? var.context.application.name : ""
  environment_name = var.context.environment != null ? var.context.environment.name : ""
  resource_group   = element(split("/", var.context.resource.id), 5)
  namespace        = var.context.runtime.kubernetes.namespace
  port             = 9000
  tag              = "1.0.0"
  storage_size     = "1Gi"
  container_input  = try(var.context.resource.properties.containerName, null)
  container_name   = local.container_input != null ? local.container_input : "data"

  # The access key ID is not sensitive. The secret key is generated by the
  # Recipe and returned through Radius managed secrets.
  access_key = "radius"

  labels = {
    "radapp.io/resource"       = local.resource_name
    "radapp.io/application"    = local.application_name
    "radapp.io/environment"    = local.environment_name
    "radapp.io/resource-type"  = replace(var.context.resource.type, "/", "-")
    "radapp.io/resource-group" = local.resource_group
  }

  # Pods and selectors also carry the unique name, so the Service never selects
  # the Pods of another resource that has the same display name.
  selector_labels = {
    "radapp.io/resource"         = local.resource_name
    "app.kubernetes.io/instance" = local.unique_name
  }

  host     = "${local.unique_name}.${local.namespace}.svc.cluster.local"
  endpoint = "http://${local.host}:${local.port}"

  # Starts RustFS, then creates the bucket named by `containerName` through the
  # S3 API on 127.0.0.1, signing the request with the root credentials. The
  # readiness probe passes only once the bucket exists. SIGTERM is forwarded to
  # the server so it shuts down cleanly.
  start_script = <<-EOT
    set -u
    if ! printf '%s' "$BUCKET_NAME" | grep -Eq '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$'; then
      echo "Invalid bucket name: $BUCKET_NAME" >&2
      exit 1
    fi
    /entrypoint.sh rustfs &
    server=$!
    trap 'kill -TERM "$server" 2>/dev/null' TERM INT
    bucket() {
      curl -fsS -o /dev/null --aws-sigv4 'aws:amz:us-east-1:s3' --user "$RUSTFS_ACCESS_KEY:$RUSTFS_SECRET_KEY" "$@" "http://127.0.0.1:9000/$BUCKET_NAME"
    }
    until bucket -I 2>/dev/null || bucket -X PUT 2>/dev/null; do
      kill -0 "$server" 2>/dev/null || break
      sleep 2
    done
    wait "$server"
    status=$?
    while kill -0 "$server" 2>/dev/null; do
      wait "$server"
      status=$?
    done
    exit "$status"
  EOT
}

# Random secret key for the object store. Terraform keeps it in the Recipe's
# state, so it stays the same when the Recipe runs again.
resource "random_password" "secret_key" {
  length  = 32
  special = false
}

resource "kubernetes_secret" "credentials" {
  metadata {
    name      = "${local.unique_name}-credentials"
    namespace = local.namespace
    labels    = local.labels
  }

  data = {
    accessKey = local.access_key
    secretKey = random_password.secret_key.result
  }
}

resource "kubernetes_persistent_volume_claim" "data" {
  # With a WaitForFirstConsumer StorageClass the claim binds only once the
  # Deployment's Pod is scheduled, so do not wait for it here.
  wait_until_bound = false

  metadata {
    name      = "${local.unique_name}-data"
    namespace = local.namespace
    labels    = local.labels
  }

  spec {
    access_modes = ["ReadWriteOnce"]

    resources {
      requests = {
        storage = local.storage_size
      }
    }
  }
}

# In-cluster object store Deployment. A single-node RustFS server, an
# S3-compatible object store, serving the S3 API over HTTP on port 9000.
resource "kubernetes_deployment" "store" {
  metadata {
    name      = local.unique_name
    namespace = local.namespace
    labels    = local.labels
  }

  spec {
    # Single-replica server on a ReadWriteOnce volume: Recreate tears down the
    # old Pod and releases the volume before the new one starts on update
    # (default RollingUpdate would briefly run both).
    strategy {
      type = "Recreate"
    }

    selector {
      match_labels = local.selector_labels
    }

    template {
      metadata {
        labels = merge(local.labels, local.selector_labels)
        annotations = {
          # A new secret key changes the Pod template, so the server restarts
          # and reads the updated Secret during deployment.
          "radapp.io/generated-secret-key-hash" = sha256(random_password.secret_key.result)
        }
      }

      spec {
        # Service links would inject variables such as RUSTFS_PORT whenever a
        # Service named `rustfs` exists in the namespace.
        enable_service_links = false

        security_context {
          # The image runs as the `rustfs` user (UID and GID 10001). fs_group
          # makes the volume writable for it on storage classes that support it.
          fs_group = 10001
        }

        container {
          name    = "rustfs"
          image   = "rustfs/rustfs:${local.tag}"
          command = ["sh", "-c", local.start_script]

          port {
            container_port = local.port
          }

          env {
            name = "RUSTFS_ACCESS_KEY"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.credentials.metadata[0].name
                key  = "accessKey"
              }
            }
          }

          env {
            name = "RUSTFS_SECRET_KEY"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.credentials.metadata[0].name
                key  = "secretKey"
              }
            }
          }

          env {
            name  = "RUSTFS_VOLUMES"
            value = "/data"
          }

          env {
            name  = "RUSTFS_ADDRESS"
            value = ":${local.port}"
          }

          # Serve only the S3 API; no web console.
          env {
            name  = "RUSTFS_CONSOLE_ENABLE"
            value = "false"
          }

          env {
            name  = "RUSTFS_CHECK_UPDATE"
            value = "false"
          }

          # Log to stdout instead of files under /logs.
          env {
            name  = "RUSTFS_OBS_LOG_DIRECTORY"
            value = ""
          }

          env {
            name  = "BUCKET_NAME"
            value = local.container_name
          }

          readiness_probe {
            exec {
              command = ["sh", "-c", "curl -fsS -o /dev/null -I --aws-sigv4 aws:amz:us-east-1:s3 --user \"$RUSTFS_ACCESS_KEY:$RUSTFS_SECRET_KEY\" \"http://127.0.0.1:9000/$BUCKET_NAME\""]
            }
            initial_delay_seconds = 2
            period_seconds        = 5
          }

          resources {
            requests = {
              memory = "256Mi"
            }
          }

          volume_mount {
            name       = "data"
            mount_path = "/data"
          }
        }

        volume {
          name = "data"
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.data.metadata[0].name
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "store" {
  metadata {
    name      = local.unique_name
    namespace = local.namespace
    labels    = local.labels
  }

  spec {
    type = "ClusterIP"

    selector = local.selector_labels

    port {
      port = local.port
    }
  }
}

output "result" {
  value = {
    resources = [
      "/planes/kubernetes/local/namespaces/${local.namespace}/providers/core/Secret/${kubernetes_secret.credentials.metadata[0].name}",
      "/planes/kubernetes/local/namespaces/${local.namespace}/providers/core/PersistentVolumeClaim/${kubernetes_persistent_volume_claim.data.metadata[0].name}",
      "/planes/kubernetes/local/namespaces/${local.namespace}/providers/core/Service/${kubernetes_service.store.metadata[0].name}",
      "/planes/kubernetes/local/namespaces/${local.namespace}/providers/apps/Deployment/${kubernetes_deployment.store.metadata[0].name}"
    ]
    values = {
      # The S3 endpoint. Clients use path-style requests (<endpoint>/<bucket>)
      # and any region name, for example us-east-1.
      endpoint = local.endpoint
      # The S3 access key ID, the counterpart of the Azure Storage account name.
      accountName = local.access_key
    }
    secrets = {
      # The S3 secret access key, generated by the Recipe. Radius materializes
      # it into the managed Radius.Security/secrets resource; it is never
      # written onto the resource.
      accountKey = random_password.secret_key.result
      # The endpoint with the credentials embedded,
      # http://<accessKey>:<secretKey>@<host>:9000.
      connectionString = "http://${local.access_key}:${random_password.secret_key.result}@${local.host}:${local.port}"
    }
  }
  sensitive = true
}
