extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// Ollama variables
//////////////////////////////////////////

var tag string = '0.34.4'
var port = 11434
var host = '${resourceName}.${namespace}.svc.cluster.local'

// `model` is the name clients send in OpenAI API requests. Hosted OpenAI model
// names such as the default `gpt-5-mini` have no open weights, so for any name
// that starts with `gpt-` (except the open-weight `gpt-oss` family) the Recipe
// pulls a small open-weight CPU model and serves it under the requested name.
// Any other value is pulled as-is from the Ollama library, for example
// `llama3.2:1b`.
var model = context.resource.properties.?model ?? 'gpt-5-mini'
var defaultModel = 'qwen2.5:0.5b'
var servesDefaultModel = startsWith(toLower(model), 'gpt-') && !startsWith(toLower(model), 'gpt-oss')
var sourceModel = servesDefaultModel ? defaultModel : model

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

// Starts the Ollama server, pulls the source model and, when it differs, copies
// it to the requested model name so requests for `model` resolve. The pull runs
// in the background so SIGTERM is forwarded to the server without waiting for a
// download to finish. A pull that still fails after five attempts stops the
// container with an error. The readiness probe passes only after the model is
// available.
var startScript = '''
set -u
ollama serve &
server=$!
trap 'kill -TERM "$server" 2>/dev/null' TERM INT
until ollama list >/dev/null 2>&1; do
  kill -0 "$server" 2>/dev/null || break
  sleep 1
done
ready=false
for attempt in 1 2 3 4 5; do
  kill -0 "$server" 2>/dev/null || break
  ollama pull "$SOURCE_MODEL" &
  if wait $!; then
    if [ "$SOURCE_MODEL" = "$MODEL_NAME" ] || ollama cp "$SOURCE_MODEL" "$MODEL_NAME"; then
      ready=true
      break
    fi
  fi
  echo "Attempt $attempt to pull model $SOURCE_MODEL failed" >&2
  sleep 5
done
if [ "$ready" = true ]; then
  touch /tmp/model-ready
elif kill -0 "$server" 2>/dev/null; then
  echo "Could not pull model $SOURCE_MODEL" >&2
  kill -TERM "$server" 2>/dev/null
  wait "$server"
  exit 1
fi
wait "$server"
status=$?
while kill -0 "$server" 2>/dev/null; do
  wait "$server"
  status=$?
done
exit "$status"
'''

//////////////////////////////////////////
// Ollama Deployment
//////////////////////////////////////////

resource ollama 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent server. Recreate ensures the old Pod is
    // torn down before the new one starts on update, so two servers never pull
    // and hold the same model at once (the default RollingUpdate would briefly
    // run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        containers: [
          {
            // The Ollama server, which serves the OpenAI-compatible API under
            // /v1 on port 11434. Inference runs on the CPU.
            name: 'ollama'
            image: 'ollama/ollama:${tag}'
            command: [
              'bash'
              '-c'
              startScript
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'SOURCE_MODEL'
                value: sourceModel
              }
              {
                name: 'MODEL_NAME'
                value: model
              }
            ]
            readinessProbe: {
              exec: {
                command: [
                  'bash'
                  '-c'
                  'test -f /tmp/model-ready'
                ]
              }
              initialDelaySeconds: 5
              periodSeconds: 5
            }
            resources: {
              requests: {
                memory: '1Gi'
              }
            }
            volumeMounts: [
              {
                name: 'models'
                mountPath: '/root/.ollama'
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'models'
            emptyDir: {}
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${ollama.metadata.namespace}/providers/apps/Deployment/${ollama.metadata.name}'
  ]
  values: {
    // The OpenAI-compatible base URL. OpenAI client libraries append paths
    // such as /chat/completions to it.
    endpoint: 'http://${host}:${port}/v1'
  }
  secrets: {
    // Ollama does not authenticate requests. OpenAI client libraries still
    // require a non-empty API key, so the Recipe returns the placeholder
    // `ollama`, which the server ignores. Radius materializes it into the
    // managed Radius.Security/secrets resource; it is never written onto the
    // resource.
    apiKey: 'ollama'
  }
}
