extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes

//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// MySQL variables
//////////////////////////////////////////

var username = context.resource.properties.username
var password = context.resource.properties.password
var database = context.resource.properties.?database ?? 'mysql_db'

@description('The major MySQL server version in the X.Y format. Defaults to the version 8.4 if not provided.')
@allowed([
  '5.7'
  '8.0'
  '8.4'
])
param version string = context.resource.properties.?version ?? '8.4'

var port = 3306

//////////////////////////////////////////
// MySQL transport policy
//
// `tls` states the transport policy for connections to the server. It maps onto
// the `require_secure_transport` system variable, which is passed as a `mysqld`
// startup flag: the official image's entrypoint prepends `mysqld` to arguments
// that begin with `--`.
//
// The variable exempts Unix socket connections, so the entrypoint's first-run
// initialization (creating the database and user over the local socket) still
// succeeds when the policy is `required`. The server also generates a
// self-signed CA and certificate into its data directory during initialization,
// so it can serve TLS without any certificate being supplied to the Recipe.
//////////////////////////////////////////

var tls = context.resource.properties.?tls ?? 'required'
var requireSecureTransport = tls == 'optional' ? 'OFF' : 'ON'

var labels = {
  'radapp.io/resource': resourceName
  'radapp.io/application': applicationName
  'radapp.io/environment': environmentName
  'radapp.io/resource-type': replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// MySQL credentials
//
// The administrator username and password are provided directly on the
// Radius.Data/mySqlDatabases resource. `password` is x-radius-sensitive, so
// Radius injects it into the Recipe decrypted. Store both in a Kubernetes
// Secret so the MySQL container references them via secretKeyRef rather than
// carrying the password inline in the Pod spec.
//////////////////////////////////////////

resource dbSecret 'core/Secret@v1' = {
  metadata: {
    name: '${resourceName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    USERNAME: username
    PASSWORD: password
  }
}

//////////////////////////////////////////
// MySQL Deployment
//////////////////////////////////////////

resource mySql 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        containers: [
          {
            // This container is the running mysql instance.
            name: 'mysql'
            image: 'mysql:${version}'
            args: [
              '--require-secure-transport=${requireSecureTransport}'
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'MYSQL_RANDOM_ROOT_PASSWORD'
                value: 'yes'
              }
              {
                name: 'MYSQL_USER'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'USERNAME'
                  }
                }
              }
              {
                name: 'MYSQL_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'PASSWORD'
                  }
                }
              }
              {
                name: 'MYSQL_DATABASE'
                value: database
              }
            ]
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//
// The administrator credentials are developer-authored Recipe inputs, not
// Recipe-generated outputs. A consuming application should author its own
// Radius.Security/secrets resource for the password (see test/app.bicep).
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${dbSecret.metadata.namespace}/providers/core/Secret/${dbSecret.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${mySql.metadata.namespace}/providers/apps/Deployment/${mySql.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: port
    database: database
  }
}
