extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Operator-owned Kubernetes TLS Secret in the database namespace, containing tls.crt and tls.key. The certificate must cover the Service hostname.')
@minLength(1)
param postgresqlTlsSecretName string = '${context.resource.name}-tls'

@description('Change this value after replacing the TLS Secret to roll out the new certificate. Back up data before rolling out this ephemeral database.')
@minLength(1)
param postgresqlTlsCertificateRevision string = '1'

var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5] 
var namespace = context.runtime.kubernetes.namespace 

//////////////////////////////////////////
// PostgreSQL variables
//////////////////////////////////////////

var username = context.resource.properties.username
var password = context.resource.properties.password
var database = context.resource.properties.?database ?? 'postgres_db'
var sizeValue = context.resource.properties.?size ?? 'S'
var initSql = context.resource.properties.?initSql ?? ''
var hasInitSql = initSql != ''
var requestedTls = context.resource.properties.?tls ?? 'required'
var tlsPolicy = contains(['required', 'optional'], requestedTls)
  ? requestedTls
  : fail('PostgreSQL tls must be required or optional.')
// Keep Unix-socket initialization available; no broad host rule may bypass TLS.
var hbaRequiredConfig = join([
  'local all all trust'
  'hostnossl all all 0.0.0.0/0 reject'
  'hostnossl all all ::/0 reject'
  'hostssl all all 0.0.0.0/0 scram-sha-256'
  'hostssl all all ::/0 scram-sha-256'
  ''
], '\n')
var hbaOptionalConfig = replace(hbaRequiredConfig, ' reject', ' scram-sha-256')
var tag string = '16-alpine'
var port = 5432
var memory ={
  S: {
    memoryRequest: '512Mi'
  } 
  M: {
    memoryRequest: '1Gi'
  }
  L: {
    memoryRequest: '2Gi'
  }
} 

var labels = {  
  'radapp.io/resource':       resourceName  
  'radapp.io/application':    applicationName  
  'radapp.io/environment':    environmentName  
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')  
  'radapp.io/resource-group': resourceGroupName  
}  

//////////////////////////////////////////
// Init SQL ConfigMap (optional)
//////////////////////////////////////////

resource initSqlConfigMap 'core/ConfigMap@v1' = if (hasInitSql) {
  metadata: {
    name: '${resourceName}-init-sql'
    namespace: namespace
    labels: labels
  }
  data: {
    '01-init.sql': initSql
  }
}

//////////////////////////////////////////
// PostgreSQL credentials
//
// The administrator username and password are provided directly on the
// Radius.Data/postgreSqlDatabases resource. `password` is x-radius-sensitive,
// so Radius injects it into the Recipe decrypted. Store both in a Kubernetes
// Secret so the PostgreSQL container references them via secretKeyRef rather
// than carrying the password inline in the Pod spec.
//////////////////////////////////////////

resource dbSecret 'core/Secret@v1' = {
  metadata: {
    name: '${resourceName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    USERNAME: username
    PASSWORD: password
  }
}

resource transportConfig 'core/ConfigMap@v1' = {
  metadata: {
    name: '${resourceName}-transport'
    namespace: namespace
    labels: labels
  }
  data: {
    // Both files are stable across policy transitions; selection happens in args.
    'pg_hba-required.conf': hbaRequiredConfig
    'pg_hba-optional.conf': hbaOptionalConfig
  }
}

//////////////////////////////////////////
// PostgreSQL Deployment
//////////////////////////////////////////


resource postgresql 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
        annotations: {
          'radapp.io-postgresql-tls-policy': tlsPolicy
          'radapp.io-postgresql-tls-revision': postgresqlTlsCertificateRevision
        }
      }
      spec: {
        initContainers: [
          {
            name: 'prepare-tls'
            image: 'postgres:${tag}'
            command: [
              '/bin/sh'
              '-ec'
              '''
test -s /tls-source/tls.crt && test -s /tls-source/tls.key || {
  echo "PostgreSQL requires a TLS Secret with nonempty tls.crt and tls.key" >&2
  exit 1
}
cp /tls-source/tls.crt /tls/server.crt
cp /tls-source/tls.key /tls/server.key
chown -R postgres:postgres /tls
chmod 700 /tls
chmod 600 /tls/server.key
chmod 644 /tls/server.crt
'''
            ]
            securityContext: {
              runAsUser: 0
            }
            volumeMounts: [
              {
                name: 'tls-source'
                mountPath: '/tls-source'
                readOnly: true
              }
              {
                name: 'tls'
                mountPath: '/tls'
              }
            ]
          }
        ]
        containers: [
          {
            // This container is the running postgresql instance.
            name: 'postgres'
            image: 'postgres:${tag}'
            args: [
              'postgres'
              '-c'
              'ssl=on'
              '-c'
              'ssl_min_protocol_version=TLSv1.2'
              '-c'
              'ssl_cert_file=/tls/server.crt'
              '-c'
              'ssl_key_file=/tls/server.key'
              '-c'
              'hba_file=/transport/pg_hba-${tlsPolicy}.conf'
              '-c'
              'password_encryption=scram-sha-256'
            ]
            readinessProbe: {
              exec: {
                command: ['pg_isready', '-q', '-h', '/var/run/postgresql']
              }
              periodSeconds: 5
              timeoutSeconds: 3
            }
            ports: [
              {
                containerPort: port 
              }
            ]
            resources: {
              requests: {
                memory: memory[sizeValue].memoryRequest
              }
            }
            env: [
              {
                name: 'POSTGRES_USER'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'USERNAME'
                  }
                }
              }
              {
                name: 'POSTGRES_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: dbSecret.metadata.name
                    key: 'PASSWORD'
                  }
                }
              }
              {
                name: 'POSTGRES_DB'
                value: database
              }
            ]
            volumeMounts: concat([
              {
                name: 'tls'
                mountPath: '/tls'
                readOnly: true
              }
              {
                name: 'transport'
                mountPath: '/transport'
                readOnly: true
              }
            ], hasInitSql ? [
              {
                name: 'init-sql'
                mountPath: '/docker-entrypoint-initdb.d'
                readOnly: true
              }
            ] : [])
          }
        ]
        volumes: concat([
          {
            name: 'tls-source'
            secret: {
              secretName: postgresqlTlsSecretName
              defaultMode: 256
              items: [
                { key: 'tls.crt', path: 'tls.crt' }
                { key: 'tls.key', path: 'tls.key' }
              ]
            }
          }
          {
            name: 'tls'
            emptyDir: {
              medium: 'Memory'
            }
          }
          {
            name: 'transport'
            configMap: {
              name: transportConfig.metadata.name
            }
          }
        ], hasInitSql ? [
          {
            name: 'init-sql'
            configMap: {
              name: initSqlConfigMap!.metadata.name
            }
          }
        ] : [])
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port 
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//
// No `result.secrets`: the administrator credentials flow *into* this Recipe as
// user-supplied properties, so there is nothing for the Recipe to hand back. An
// application that needs the password for a consuming container already holds it
// and should author its own Radius.Security/secrets resource, binding it with
// `valueFrom.secretKeyRef` (see test/app.bicep). This matches the Azure recipe in
// recipe-packs/azure-aks/azure-aks.bicep, which maps only `host`. Contrast with
// redisCaches, where the access key is generated by the infrastructure and so is
// returned via `result.secrets`.
//////////////////////////////////////////

output result object = {
  resources: union(
    [
      '/planes/kubernetes/local/namespaces/${dbSecret.metadata.namespace}/providers/core/Secret/${dbSecret.metadata.name}'
      '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
      '/planes/kubernetes/local/namespaces/${postgresql.metadata.namespace}/providers/apps/Deployment/${postgresql.metadata.name}'
      '/planes/kubernetes/local/namespaces/${transportConfig.metadata.namespace}/providers/core/ConfigMap/${transportConfig.metadata.name}'
    ],
    hasInitSql ? [
      '/planes/kubernetes/local/namespaces/${initSqlConfigMap!.metadata.namespace}/providers/core/ConfigMap/${initSqlConfigMap!.metadata.name}'
    ] : []
  )
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: port
    database: database
  }
}
