extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
// A unique per-resource name so two rabbitMQ resources that share a display name
// (or the same name across recreates) never collide on their Kubernetes objects.
var uniqueName = '${resourceName}-${uniqueString(context.resource.id)}'
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// RabbitMQ variables
//////////////////////////////////////////

var tag string = '4-alpine'
var port = 5672

// The default `guest` account is restricted to loopback connections, so a client
// running in another Pod cannot authenticate as `guest`. A non-`guest` user is not
// loopback-restricted, so the broker accepts AMQP connections from workload Pods.
// The username/password come from the resource properties when supplied; otherwise
// the Recipe falls back to a default user and a generated password. Either way the
// credentials are materialized into the managed Radius.Security/secrets resource via
// the connectionString output below, and are never written onto the rabbitMQ resource.
var username = context.resource.properties.?username ?? 'radius'
var password = context.resource.properties.?password ?? uniqueString(context.resource.id, 'rabbitmq')

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// RabbitMQ credentials
//
// Store the generated broker credentials in a Kubernetes Secret so the RabbitMQ
// container references them via secretKeyRef rather than carrying them inline in the
// Pod spec (consistent with the MySQL/PostgreSQL Kubernetes recipes).
//////////////////////////////////////////

resource brokerSecret 'core/Secret@v1' = {
  metadata: {
    name: '${uniqueName}-credentials'
    namespace: namespace
    labels: labels
  }
  stringData: {
    USERNAME: username
    PASSWORD: password
  }
}

//////////////////////////////////////////
// RabbitMQ Deployment
//////////////////////////////////////////

resource rabbitmq 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent broker. Recreate ensures the old Pod is torn
    // down before the new one starts on update, so two divergent brokers never serve
    // the same Service at once (the default RollingUpdate would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        containers: [
          {
            // The running RabbitMQ broker. RABBITMQ_DEFAULT_USER/PASS provision a
            // non-loopback user on first start so workload Pods can authenticate over
            // AMQP 0-9-1 on port 5672.
            name: 'rabbitmq'
            image: 'rabbitmq:${tag}'
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'RABBITMQ_DEFAULT_USER'
                valueFrom: {
                  secretKeyRef: {
                    name: brokerSecret.metadata.name
                    key: 'USERNAME'
                  }
                }
              }
              {
                name: 'RABBITMQ_DEFAULT_PASS'
                valueFrom: {
                  secretKeyRef: {
                    name: brokerSecret.metadata.name
                    key: 'PASSWORD'
                  }
                }
              }
            ]
            resources: {
              requests: {
                memory: '256Mi'
              }
              limits: {
                memory: '1Gi'
              }
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

var host = '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${brokerSecret.metadata.namespace}/providers/core/Secret/${brokerSecret.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${rabbitmq.metadata.namespace}/providers/apps/Deployment/${rabbitmq.metadata.name}'
  ]
  values: {
    host: host
  }
  secrets: {
    // A RabbitMQ AMQP 0-9-1 URI (amqp://user:pass@host:5672) — the format
    // RabbitMQ clients expect. Radius materializes it into the managed
    // Radius.Security/secrets resource; it is never written onto the resource.
    connectionString: 'amqp://${username}:${password}@${host}:${port}'
  }
}
