extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
// A unique per-resource name so two rabbitMQ resources that share a display name
// (or the same name across recreates) never collide on their Kubernetes objects.
var uniqueName = '${resourceName}-${uniqueString(context.resource.id)}'
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// RabbitMQ variables
//////////////////////////////////////////

var tag string = '4-alpine'
var port = 5672

// The default `guest` account is restricted to loopback connections, so a client
// running in another Pod cannot authenticate as `guest`. A non-`guest` user is not
// loopback-restricted, so the broker accepts AMQP connections from workload Pods.
// The username/password come from the resource properties when supplied; otherwise
// the Recipe falls back to a default user and a generated password. Either way the
// credentials are materialized into the managed Radius.Security/secrets resource via
// the connectionString output below, and are never written onto the rabbitMQ resource.
var username = context.resource.properties.?username ?? 'radius'
var password = context.resource.properties.?password ?? uniqueString(context.resource.id, 'rabbitmq')

// The queue is pre-provisioned on the broker (see the definitions ConfigMap and the
// init container below) so the named queue exists as soon as the broker is ready,
// rather than relying on a client to declare it first.
var queue = context.resource.properties.?queue ?? 'jobs'

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// RabbitMQ definitions import config
//
// Point the broker at a definitions file (written by the init container below) so it
// imports the vhost, user, permissions, and the pre-provisioned queue on boot. The
// file lives in a shared emptyDir; this ConfigMap only carries the small conf.d
// snippet that enables the import.
//////////////////////////////////////////

resource brokerConfig 'core/ConfigMap@v1' = {
  metadata: {
    name: '${uniqueName}-config'
    namespace: namespace
    labels: labels
  }
  data: {
    '20-definitions.conf': join([
      'definitions.import_backend = local_filesystem'
      'definitions.local.path = /etc/rabbitmq/definitions/definitions.json'
    ], '\n')
  }
}

//////////////////////////////////////////
// RabbitMQ Deployment
//////////////////////////////////////////

resource rabbitmq 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent broker. Recreate ensures the old Pod is torn
    // down before the new one starts on update, so two divergent brokers never serve
    // the same Service at once (the default RollingUpdate would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        // Generate the broker definitions file (vhost, user, permissions, and the
        // pre-provisioned queue) into a shared volume before the broker starts.
        // rabbitmqctl hash_password computes the password hash offline, so the
        // plaintext password is only read from the mounted Secret and is never baked
        // into the definitions file or the image.
        initContainers: [
          {
            name: 'generate-definitions'
            image: 'rabbitmq:${tag}'
            command: [
              'sh'
              '-c'
              'set -eu\nHASH=$(rabbitmqctl hash_password "$RABBITMQ_PASSWORD" | tail -n1 | tr -d \'[:space:]\')\nprintf \'{"users":[{"name":"%s","password_hash":"%s","hashing_algorithm":"rabbit_password_hashing_sha256","tags":["administrator"]}],"vhosts":[{"name":"/"}],"permissions":[{"user":"%s","vhost":"/","configure":".*","write":".*","read":".*"}],"queues":[{"name":"%s","vhost":"/","durable":true,"auto_delete":false,"arguments":{}}],"exchanges":[],"bindings":[]}\\n\' "$RABBITMQ_USER" "$HASH" "$RABBITMQ_USER" "$RABBITMQ_QUEUE" > /etc/rabbitmq/definitions/definitions.json'
            ]
            env: [
              {
                name: 'RABBITMQ_USER'
                value: username
              }
              {
                name: 'RABBITMQ_PASSWORD'
                value: password
              }
              {
                name: 'RABBITMQ_QUEUE'
                value: queue
              }
            ]
            volumeMounts: [
              {
                name: 'definitions'
                mountPath: '/etc/rabbitmq/definitions'
              }
            ]
          }
        ]
        containers: [
          {
            // The running RabbitMQ broker. On boot it imports the definitions file,
            // which creates the non-loopback user and the pre-provisioned queue, then
            // accepts AMQP 0-9-1 connections from workload Pods on port 5672.
            name: 'rabbitmq'
            image: 'rabbitmq:${tag}'
            ports: [
              {
                containerPort: port
              }
            ]
            volumeMounts: [
              {
                name: 'definitions'
                mountPath: '/etc/rabbitmq/definitions'
                readOnly: true
              }
              {
                name: 'config'
                mountPath: '/etc/rabbitmq/conf.d/20-definitions.conf'
                subPath: '20-definitions.conf'
                readOnly: true
              }
            ]
            resources: {
              requests: {
                memory: '256Mi'
              }
              limits: {
                memory: '1Gi'
              }
            }
          }
        ]
        volumes: [
          {
            name: 'definitions'
            emptyDir: {}
          }
          {
            name: 'config'
            configMap: {
              name: brokerConfig.metadata.name
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

var host = '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${brokerConfig.metadata.namespace}/providers/core/ConfigMap/${brokerConfig.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${rabbitmq.metadata.namespace}/providers/apps/Deployment/${rabbitmq.metadata.name}'
  ]
  values: {
    host: host
  }
  secrets: {
    // A RabbitMQ AMQP 0-9-1 URI (amqp://user:pass@host:5672) — the format
    // RabbitMQ clients expect. Radius materializes it into the managed
    // Radius.Security/secrets resource; it is never written onto the resource.
    connectionString: 'amqp://${username}:${password}@${host}:${port}'
  }
}
