extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
// A unique per-resource name so two rabbitMQ resources that share a display name
// (or the same name across recreates) never collide on their Kubernetes objects.
var uniqueName = '${resourceName}-${uniqueString(context.resource.id)}'
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// RabbitMQ variables
//////////////////////////////////////////

var tag string = '4-alpine'
var port = 5672

// The default `guest` account is restricted to loopback connections, so a client
// running in another Pod cannot authenticate as `guest`. A non-`guest` user is not
// loopback-restricted, so the broker accepts AMQP connections from workload Pods.
// The username is not sensitive and comes from the resource properties (default
// `radius`). The password is NOT passed to the Recipe in plaintext: the developer
// supplies it via a Radius.Security/secrets resource and references that resource's
// ID on the `passwordSecret` property. The Recipe derives the materialized
// Kubernetes Secret name from that ID and mounts the password into the broker via
// `secretKeyRef`, so the plaintext password is never written into the pod spec.
var username = context.resource.properties.?username ?? 'radius'

// Resource ID of the developer-supplied Radius.Security/secrets resource. The
// Kubernetes secrets Recipe names the materialized Secret after the resource name,
// which is the last segment of the resource ID.
var passwordSecretId = context.resource.properties.passwordSecret
var credentialsSecretName = last(split(passwordSecretId, '/'))

// The queue is pre-provisioned on the broker (see the definitions ConfigMap and the
// init container below) so the named queue exists as soon as the broker is ready,
// rather than relying on a client to declare it first.
var queue = context.resource.properties.?queue ?? 'jobs'

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

//////////////////////////////////////////
// RabbitMQ definitions import config
//
// Point the broker at a definitions file (written by the init container below) so it
// imports the vhost, user, permissions, and the pre-provisioned queue on boot. The
// file lives in a shared emptyDir; this ConfigMap only carries the small conf.d
// snippet that enables the import.
//////////////////////////////////////////

resource brokerConfig 'core/ConfigMap@v1' = {
  metadata: {
    name: '${uniqueName}-config'
    namespace: namespace
    labels: labels
  }
  data: {
    '20-definitions.conf': join([
      'definitions.import_backend = local_filesystem'
      'definitions.local.path = /etc/rabbitmq/definitions/definitions.json'
    ], '\n')
  }
}

//////////////////////////////////////////
// RabbitMQ Deployment
//////////////////////////////////////////

resource rabbitmq 'apps/Deployment@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent broker. Recreate ensures the old Pod is torn
    // down before the new one starts on update, so two divergent brokers never serve
    // the same Service at once (the default RollingUpdate would briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        // Generate the broker definitions file (vhost, user, permissions, and the
        // pre-provisioned queue) into a shared volume before the broker starts.
        // rabbitmqctl hash_password computes the password hash offline. The plaintext
        // password is injected only at runtime from the developer-supplied
        // Radius.Security/secrets Kubernetes Secret via secretKeyRef; it is never
        // baked into the pod spec, the definitions file, or the image.
        initContainers: [
          {
            name: 'generate-definitions'
            image: 'rabbitmq:${tag}'
            command: [
              'sh'
              '-c'
              'set -eu\nHASH=$(rabbitmqctl hash_password "$RABBITMQ_PASSWORD" | tail -n1 | tr -d \'[:space:]\')\nprintf \'{"users":[{"name":"%s","password_hash":"%s","hashing_algorithm":"rabbit_password_hashing_sha256","tags":["administrator"]}],"vhosts":[{"name":"/"}],"permissions":[{"user":"%s","vhost":"/","configure":".*","write":".*","read":".*"}],"queues":[{"name":"%s","vhost":"/","durable":true,"auto_delete":false,"arguments":{}}],"exchanges":[],"bindings":[]}\\n\' "$RABBITMQ_USER" "$HASH" "$RABBITMQ_USER" "$RABBITMQ_QUEUE" > /etc/rabbitmq/definitions/definitions.json'
            ]
            env: [
              {
                name: 'RABBITMQ_USER'
                value: username
              }
              {
                // Sourced from the developer-supplied Radius.Security/secrets
                // Kubernetes Secret — never a literal value in the pod spec.
                name: 'RABBITMQ_PASSWORD'
                valueFrom: {
                  secretKeyRef: {
                    name: credentialsSecretName
                    key: 'password'
                  }
                }
              }
              {
                name: 'RABBITMQ_QUEUE'
                value: queue
              }
            ]
            volumeMounts: [
              {
                name: 'definitions'
                mountPath: '/etc/rabbitmq/definitions'
              }
            ]
          }
        ]
        containers: [
          {
            // The running RabbitMQ broker. On boot it imports the definitions file,
            // which creates the non-loopback user and the pre-provisioned queue, then
            // accepts AMQP 0-9-1 connections from workload Pods on port 5672.
            name: 'rabbitmq'
            image: 'rabbitmq:${tag}'
            ports: [
              {
                containerPort: port
              }
            ]
            volumeMounts: [
              {
                name: 'definitions'
                mountPath: '/etc/rabbitmq/definitions'
                readOnly: true
              }
              {
                name: 'config'
                mountPath: '/etc/rabbitmq/conf.d/20-definitions.conf'
                subPath: '20-definitions.conf'
                readOnly: true
              }
            ]
            resources: {
              requests: {
                memory: '256Mi'
              }
              limits: {
                memory: '1Gi'
              }
            }
          }
        ]
        volumes: [
          {
            name: 'definitions'
            emptyDir: {}
          }
          {
            name: 'config'
            configMap: {
              name: brokerConfig.metadata.name
            }
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: uniqueName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

var host = '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${brokerConfig.metadata.namespace}/providers/core/ConfigMap/${brokerConfig.metadata.name}'
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${rabbitmq.metadata.namespace}/providers/apps/Deployment/${rabbitmq.metadata.name}'
  ]
  values: {
    // Non-secret connection values. Clients build their AMQP 0-9-1 connection from
    // these plus the password, which they read directly from the same
    // Radius.Security/secrets resource (via secretKeyRef) — the Recipe never sees
    // or emits the plaintext password.
    host: host
    port: port
    username: username
  }
}
