variable "context" {
  description = "Information about what resource is calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.dev/operations/custom-recipes/"
  type        = any
}

variable "csi_driver" {
  description = "CSI driver for the persistent volume"
  type        = string
  default     = "csi.example.com"
}

variable "csi_volume_handle" {
  description = "CSI volume handle for the persistent volume"
  type        = string
  default     = "default-volume"
}

variable "storage_class" {
  description = "StorageClass name to set on the PersistentVolume"
  type        = string
  default     = ""
}

