extension kubernetes with {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
} as kubernetes


//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object
var resourceName = context.resource.name
var applicationName = context.application != null ? context.application.name : ''
var environmentName = context.environment != null ? context.environment.name : ''
var resourceGroupName = split(context.resource.id, '/')[5]
var namespace = context.runtime.kubernetes.namespace

//////////////////////////////////////////
// Kafka variables
//////////////////////////////////////////

var topic = context.resource.properties.?topic ?? 'events'
var tag string = '4.3.1'
var port = 9092
var host = '${resourceName}.${namespace}.svc.cluster.local'

var labels = {
  'radapp.io/resource':       resourceName
  'radapp.io/application':    applicationName
  'radapp.io/environment':    environmentName
  'radapp.io/resource-type':  replace(context.resource.type, '/', '-')
  'radapp.io/resource-group': resourceGroupName
}

// Starts the broker, then creates the topic through the in-Pod LOCAL listener
// (127.0.0.1:9094). The PLAINTEXT listener advertises the Service DNS name,
// which has no endpoints until the Pod is ready, so the topic cannot be
// created through it. The readiness probe passes only after the topic exists.
// SIGTERM is forwarded to the broker so it shuts down cleanly.
var startScript = '''
set -u
if ! [[ "$TOPIC_NAME" =~ ^[A-Za-z0-9._-]{1,249}$ ]] || [[ "$TOPIC_NAME" == "." || "$TOPIC_NAME" == ".." ]]; then
  echo "Invalid Kafka topic name: $TOPIC_NAME" >&2
  exit 1
fi
/etc/kafka/docker/run &
broker=$!
trap 'kill -TERM "$broker" 2>/dev/null' TERM INT
until (exec 3<>/dev/tcp/127.0.0.1/9094) 2>/dev/null; do
  kill -0 "$broker" 2>/dev/null || break
  sleep 1
done
until KAFKA_HEAP_OPTS=-Xmx256m /opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9094 --create --if-not-exists --topic "$TOPIC_NAME" --partitions 1 --replication-factor 1; do
  kill -0 "$broker" 2>/dev/null || break
  sleep 2
done
if kill -0 "$broker" 2>/dev/null; then
  touch /tmp/topic-ready
fi
wait "$broker"
status=$?
while kill -0 "$broker" 2>/dev/null; do
  wait "$broker"
  status=$?
done
exit "$status"
'''

//////////////////////////////////////////
// Kafka Deployment
//////////////////////////////////////////

resource kafka 'apps/Deployment@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    // A single-replica, non-persistent broker. Recreate ensures the old Pod is
    // torn down before the new one starts on update, so two divergent brokers
    // never serve the same Service at once (the default RollingUpdate would
    // briefly run both).
    strategy: {
      type: 'Recreate'
    }
    selector: {
      matchLabels: {
        'radapp.io/resource': resourceName
      }
    }
    template: {
      metadata: {
        labels: labels
      }
      spec: {
        // The image turns every KAFKA_* variable into a broker setting. Service
        // links would inject KAFKA_SERVICE_HOST, KAFKA_PORT and similar
        // variables whenever a Service named `kafka` exists in the namespace.
        enableServiceLinks: false
        containers: [
          {
            // A single Apache Kafka node in KRaft mode, acting as both broker
            // and controller. Clients connect over plaintext on port 9092.
            name: 'kafka'
            image: 'apache/kafka:${tag}'
            command: [
              'bash'
              '-c'
              startScript
            ]
            ports: [
              {
                containerPort: port
              }
            ]
            env: [
              {
                name: 'KAFKA_NODE_ID'
                value: '1'
              }
              {
                name: 'KAFKA_PROCESS_ROLES'
                value: 'broker,controller'
              }
              {
                name: 'KAFKA_LISTENERS'
                value: 'PLAINTEXT://:${port},CONTROLLER://localhost:9093,LOCAL://127.0.0.1:9094'
              }
              {
                name: 'KAFKA_ADVERTISED_LISTENERS'
                value: 'PLAINTEXT://${host}:${port},LOCAL://127.0.0.1:9094'
              }
              {
                name: 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP'
                value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT'
              }
              {
                name: 'KAFKA_CONTROLLER_LISTENER_NAMES'
                value: 'CONTROLLER'
              }
              {
                // The single node only ever talks to itself, so keep broker
                // traffic on the in-Pod listener rather than the Service.
                name: 'KAFKA_INTER_BROKER_LISTENER_NAME'
                value: 'LOCAL'
              }
              {
                name: 'KAFKA_CONTROLLER_QUORUM_VOTERS'
                value: '1@localhost:9093'
              }
              {
                name: 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR'
                value: '1'
              }
              {
                name: 'KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR'
                value: '1'
              }
              {
                name: 'KAFKA_TRANSACTION_STATE_LOG_MIN_ISR'
                value: '1'
              }
              {
                name: 'KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR'
                value: '1'
              }
              {
                name: 'KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR'
                value: '1'
              }
              {
                name: 'KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS'
                value: '0'
              }
              {
                name: 'KAFKA_LOG_DIRS'
                value: '/var/lib/kafka/data'
              }
              {
                name: 'KAFKA_HEAP_OPTS'
                value: '-Xms512m -Xmx512m'
              }
              {
                name: 'TOPIC_NAME'
                value: topic
              }
            ]
            readinessProbe: {
              exec: {
                command: [
                  'bash'
                  '-c'
                  'test -f /tmp/topic-ready'
                ]
              }
              initialDelaySeconds: 5
              periodSeconds: 5
            }
            resources: {
              requests: {
                memory: '1Gi'
              }
            }
            volumeMounts: [
              {
                name: 'data'
                mountPath: '/var/lib/kafka/data'
              }
            ]
          }
        ]
        volumes: [
          {
            name: 'data'
            emptyDir: {}
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: resourceName
    namespace: namespace
    labels: labels
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      'radapp.io/resource': resourceName
    }
    ports: [
      {
        port: port
      }
    ]
  }
}

//////////////////////////////////////////
// Output Radius result
//////////////////////////////////////////

output result object = {
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${kafka.metadata.namespace}/providers/apps/Deployment/${kafka.metadata.name}'
  ]
  values: {
    host: host
  }
  secrets: {
    // The in-cluster broker runs without TLS or authentication, so the
    // connection string is the plain bootstrap server `host:9092`. Radius still
    // materializes it into the managed Radius.Security/secrets resource; it is
    // never written onto the resource.
    connectionString: '${host}:${port}'
  }
}
