/*
Copyright 2025 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-embed is a code generator that produces manifests_gen.go.
//
// It reads defaults.yaml to determine which resource type manifests should be
// embedded into the Radius binary, resolves each canonical resource type name
// (e.g., Radius.Compute/containers) to its manifest file path (e.g.,
// Compute/containers/containers.yaml), validates that all files exist, and
// writes manifests_gen.go containing //go:embed directives for those files.
//
// The generated manifests_gen.go exports DefaultManifests (embed.FS), which the
// Radius binary imports to register default resource types at startup.
//
// Usage:
//
//	go generate ./...          # from the repository root
//	go run ./cmd/gen-embed     # direct invocation
//	make generate-defaults     # via Makefile target
//
// This tool expects to be run from the repository root directory where
// defaults.yaml is located.
package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// licenseHeader is prepended to the generated manifests_gen.go file to satisfy
// the repository's license header requirement for all Go source files.
const licenseHeader = `/*
Copyright 2025 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

`

// defaultsConfig mirrors the structure of defaults.yaml.
type defaultsConfig struct {
	DefaultRegistration []string `yaml:"defaultRegistration"`
}

func main() {
	// Step 1: Read and parse defaults.yaml with strict mode so typos in field
	// names (e.g., "defaultRegistrations" with an s) are caught immediately.
	data, err := os.ReadFile("defaults.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read defaults.yaml: %v\n", err)
		os.Exit(1)
	}

	var config defaultsConfig
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	if err := decoder.Decode(&config); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse defaults.yaml: %v\n", err)
		os.Exit(1)
	}

	if len(config.DefaultRegistration) == 0 {
		fmt.Fprintln(os.Stderr, "no entries found in defaults.yaml")
		os.Exit(1)
	}

	// Step 2: Resolve each resource type name to a file path and validate.
	// Detect duplicate entries (which would produce duplicate //go:embed directives
	// and cause a compile error in the generated file).
	seen := map[string]bool{}
	var paths []string
	for _, resourceType := range config.DefaultRegistration {
		if seen[resourceType] {
			fmt.Fprintf(os.Stderr, "duplicate entry in defaults.yaml: %s\n", resourceType)
			os.Exit(1)
		}
		seen[resourceType] = true

		path, err := resolveResourceTypePath(resourceType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to resolve resource type %s: %v\n", resourceType, err)
			os.Exit(1)
		}

		if _, err := os.Stat(path); err != nil {
			fmt.Fprintf(os.Stderr, "manifest file not found for %s (resolved to %s)\n", resourceType, path)
			os.Exit(1)
		}

		paths = append(paths, path)
	}

	// Step 3: Generate manifests_gen.go with //go:embed directives.
	// The generated file embeds defaults.yaml (so the Radius binary can read the
	// list of defaults at runtime) plus each resolved manifest YAML file.
	var sb strings.Builder
	sb.WriteString(licenseHeader)
	sb.WriteString("// Code generated by gen-embed; DO NOT EDIT.\n\n")
	sb.WriteString("package resourcetypes\n\n")
	sb.WriteString("import \"embed\"\n\n")
	sb.WriteString("// DefaultManifests contains the embedded resource type manifests for default registration.\n")
	sb.WriteString("//\n")
	sb.WriteString("//go:embed defaults.yaml\n")
	for _, path := range paths {
		sb.WriteString(fmt.Sprintf("//go:embed %s\n", path))
	}
	sb.WriteString("var DefaultManifests embed.FS\n")

	// Format the generated Go source for consistency.
	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format manifests_gen.go: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("manifests_gen.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write manifests_gen.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated manifests_gen.go with %d manifest(s)\n", len(paths))
}

// resolveResourceTypePath converts a canonical resource type name to a file path.
//
// The convention is:
//   - Input:  Radius.<Namespace>/<typeName>
//   - Output: <Namespace>/<typeName>/<typeName>.yaml
//   - Example: Radius.Compute/containers -> Compute/containers/containers.yaml
//
// This matches the directory structure of resource-types-contrib where each
// resource type has its manifest at <Namespace>/<typeName>/<typeName>.yaml.
func resolveResourceTypePath(name string) (string, error) {
	parts := strings.SplitN(name, "/", 2)
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid resource type name %q: expected format Radius.<Namespace>/<typeName>", name)
	}

	namespace := parts[0]
	typeName := parts[1]

	if !strings.HasPrefix(namespace, "Radius.") {
		return "", fmt.Errorf("invalid namespace %q: must start with 'Radius.'", namespace)
	}

	// Strip "Radius." prefix to get the directory name.
	namespaceSuffix := strings.TrimPrefix(namespace, "Radius.")

	// Validate segments do not contain path traversal or invalid characters.
	for _, segment := range []string{namespaceSuffix, typeName} {
		if segment == "" {
			return "", fmt.Errorf("invalid resource type name %q: namespace suffix and type name must not be empty", name)
		}
		if strings.Contains(segment, "/") || strings.Contains(segment, "\\") || strings.Contains(segment, "..") {
			return "", fmt.Errorf("invalid resource type name %q: segments must not contain '/', '\\', or '..'", name)
		}
	}

	return fmt.Sprintf("%s/%s/%s.yaml", namespaceSuffix, typeName, typeName), nil
}
