/*
Copyright 2025 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// gen-embed reads defaults.yaml and generates manifests_gen.go with //go:embed
// directives for each listed manifest file. It resolves canonical resource type
// names (e.g., Radius.Compute/containers) to file paths (e.g.,
// Compute/containers/containers.yaml) and validates that all resolved files exist.
//
// This tool is invoked via `go generate` from the package root and expects to be
// run from the repository root directory where defaults.yaml is located.
package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

const licenseHeader = `/*
Copyright 2025 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

`

type defaultsConfig struct {
	DefaultRegistration []string `yaml:"defaultRegistration"`
}

func main() {
	data, err := os.ReadFile("defaults.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read defaults.yaml: %v\n", err)
		os.Exit(1)
	}

	var config defaultsConfig
	decoder := yaml.NewDecoder(strings.NewReader(string(data)))
	decoder.KnownFields(true)
	if err := decoder.Decode(&config); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse defaults.yaml: %v\n", err)
		os.Exit(1)
	}

	if len(config.DefaultRegistration) == 0 {
		fmt.Fprintln(os.Stderr, "no entries found in defaults.yaml")
		os.Exit(1)
	}

	// Detect duplicate entries.
	seen := map[string]bool{}
	var paths []string
	for _, resourceType := range config.DefaultRegistration {
		if seen[resourceType] {
			fmt.Fprintf(os.Stderr, "duplicate entry in defaults.yaml: %s\n", resourceType)
			os.Exit(1)
		}
		seen[resourceType] = true

		path, err := resolveResourceTypePath(resourceType)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to resolve resource type %s: %v\n", resourceType, err)
			os.Exit(1)
		}

		if _, err := os.Stat(path); err != nil {
			fmt.Fprintf(os.Stderr, "manifest file not found for %s (resolved to %s)\n", resourceType, path)
			os.Exit(1)
		}

		paths = append(paths, path)
	}

	var sb strings.Builder
	sb.WriteString(licenseHeader)
	sb.WriteString("// Code generated by gen-embed; DO NOT EDIT.\n\n")
	sb.WriteString("package resourcetypes\n\n")
	sb.WriteString("import \"embed\"\n\n")
	sb.WriteString("// DefaultManifests contains the embedded resource type manifests for default registration.\n")
	sb.WriteString("//\n")
	sb.WriteString("//go:embed defaults.yaml\n")
	for _, path := range paths {
		sb.WriteString(fmt.Sprintf("//go:embed %s\n", path))
	}
	sb.WriteString("var DefaultManifests embed.FS\n")

	formatted, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to format manifests_gen.go: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("manifests_gen.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write manifests_gen.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated manifests_gen.go with %d manifest(s)\n", len(paths))
}

// resolveResourceTypePath converts a canonical resource type name to a file path.
// Format: Radius.<Namespace>/<typeName> -> <Namespace>/<typeName>/<typeName>.yaml
// Example: Radius.Compute/containers -> Compute/containers/containers.yaml
func resolveResourceTypePath(name string) (string, error) {
	parts := strings.SplitN(name, "/", 2)
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid resource type name %q: expected format Radius.<Namespace>/<typeName>", name)
	}

	namespace := parts[0]
	typeName := parts[1]

	if !strings.HasPrefix(namespace, "Radius.") {
		return "", fmt.Errorf("invalid namespace %q: must start with 'Radius.'", namespace)
	}

	// Strip "Radius." prefix
	namespaceSuffix := strings.TrimPrefix(namespace, "Radius.")

	// Validate segments do not contain path traversal or invalid characters.
	for _, segment := range []string{namespaceSuffix, typeName} {
		if segment == "" {
			return "", fmt.Errorf("invalid resource type name %q: namespace suffix and type name must not be empty", name)
		}
		if strings.Contains(segment, "/") || strings.Contains(segment, "\\") || strings.Contains(segment, "..") {
			return "", fmt.Errorf("invalid resource type name %q: segments must not contain '/', '\\', or '..'", name)
		}
	}

	return fmt.Sprintf("%s/%s/%s.yaml", namespaceSuffix, typeName, typeName), nil
}
