variable "context" {
  description = "Information about the resource calling this Recipe. Generated by Radius. For more information visit https://docs.radapp.io/reference/context-schema/"
  type = any
}

variable "memory" {
  description = "Memory limits for the Redis container"
  type = map(object({
    memoryRequest = string
    memoryLimit  = string
  }))
  default = {
    S = {
      memoryRequest = "512Mi"
      memoryLimit   = "1024Mi"
    },
    M = {
      memoryRequest = "1Gi"
      memoryLimit   = "2Gi"
    }
    L = {
      memoryRequest = "2Gi"
      memoryLimit   = "4Gi"
    }
  }
}