targetScope = 'resourceGroup'

//////////////////////////////////////////
// Common Radius variables
//////////////////////////////////////////

@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for the flexible server. Defaults to the current resource group location.')
param location string = resourceGroup().location

//////////////////////////////////////////
// PostgreSQL variables
//////////////////////////////////////////

var username = context.resource.properties.username
var password = context.resource.properties.password
var database = context.resource.properties.?database ?? 'postgres_db'
var size = context.resource.properties.?size ?? 'S'

// PostgreSQL flexible server always listens on 5432. The AVM module this Recipe
// replaces declared no port output, so the value is stated here to keep the
// resource type's `port` contract populated on Azure. The type declares `port`
// as a string, so it is emitted as one.
var port = '5432'

@description('The major PostgreSQL server version.')
param version string = '16'

@description('Provisioned storage for the flexible server, in GiB.')
param storageSizeGB int = 32

@description('Additional PostgreSQL server parameters to apply, each of the shape { name, value }. Most commonly used to allow-list extensions via azure.extensions, for example [{ name: \'azure.extensions\', value: \'vector\' }] to enable pgvector. require_secure_transport is owned by this Recipe and reported through sslMode, so it must not be set here.')
param serverConfigurations array = []

// The type's `size` maps onto a concrete SKU, matching the mapping the Azure
// Recipe Pack applied while this type referenced the AVM module directly.
var skuName = size == 'S' ? 'Standard_B1ms' : 'Standard_D2ds_v5'
var tier = size == 'S' ? 'Burstable' : 'GeneralPurpose'

// Globally unique Azure names use a stable hash over the Radius resource ID and
// the target resource group.
var serverName = toLower('pgsql-${take(uniqueString(context.resource.id, resourceGroup().id), 16)}')

// Azure tag names cannot contain '/', so the Radius labels use '-'. `application`
// is optional on this type, so it is reached with safe navigation: ARM resolves a
// plain property path before evaluating any fallback, and would fail the
// deployment outright if the key were absent.
var tags = {
  'radapp.io-resource': context.resource.name
  'radapp.io-application': context.?application.?name ?? ''
  'radapp.io-environment': context.?environment.?name ?? ''
  'radapp.io-resource-type': replace(context.resource.type, '/', '-')
}

//////////////////////////////////////////
// PostgreSQL flexible server
//
// Azure Database for PostgreSQL flexible server runs with
// require_secure_transport = on. This Recipe deliberately keeps that default
// rather than weakening it to match the Kubernetes Recipe, and reports the
// requirement through the resource type's `sslMode` output so a connecting
// application can negotiate TLS instead of discovering the requirement from a
// failed connection.
//
// The type's optional `initSql` property is not applied here. It seeds the
// container-based Kubernetes Recipe through the postgres image's
// docker-entrypoint-initdb.d hook, which a managed flexible server does not
// expose.
//////////////////////////////////////////

resource flexibleServer 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' = {
  name: serverName
  location: location
  tags: tags
  sku: {
    name: skuName
    tier: tier
  }
  properties: {
    administratorLogin: username
    // Radius injects `password` decrypted from the resource's
    // x-radius-sensitive property, so the value is secret despite arriving
    // through the untyped `context` object the linter cannot see into.
    #disable-next-line use-secure-value-for-secure-inputs
    administratorLoginPassword: password
    version: version
    authConfig: {
      // The Recipe authenticates with the administrator username and password
      // from the resource, and never uses Entra ID. Enabling activeDirectoryAuth
      // would buy nothing here and would require a tenantId that this Recipe has
      // no reliable way to determine.
      activeDirectoryAuth: 'Disabled'
      passwordAuth: 'Enabled'
    }
    storage: {
      storageSizeGB: storageSizeGB
    }
    backup: {
      backupRetentionDays: 7
      geoRedundantBackup: 'Disabled'
    }
    highAvailability: {
      mode: 'Disabled'
    }
    network: {
      publicNetworkAccess: 'Enabled'
    }
  }
}

resource postgresDatabase 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' = {
  parent: flexibleServer
  name: database
  properties: {
    charset: 'UTF8'
    collation: 'en_US.utf8'
  }
}

// Matches the connectivity the Azure Recipe Pack provided previously: the
// database has to be reachable from the application's cluster, which is not
// necessarily inside the server's virtual network.
resource allowAll 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: flexibleServer
  name: 'allow-all'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '255.255.255.255'
  }
}

// `source` is set explicitly: the ARM contract for PostgreSQL flexible server
// configurations requires it to update the value of a modifiable parameter, and
// omitting it can leave the parameter at its system default while the
// deployment still reports success.
//
// Applied one at a time because the server rejects concurrent configuration
// writes, and after the database so the two do not contend for the server.
@batchSize(1)
resource configurations 'Microsoft.DBforPostgreSQL/flexibleServers/configurations@2024-08-01' = [
  for configuration in serverConfigurations: {
    parent: flexibleServer
    name: configuration.name
    properties: {
      source: 'user-override'
      value: configuration.value
    }
    dependsOn: [
      postgresDatabase
      allowAll
    ]
  }
]

//////////////////////////////////////////
// Output
//////////////////////////////////////////

output result object = {
  resources: [
    flexibleServer.id
  ]
  values: {
    host: flexibleServer.properties.fullyQualifiedDomainName
    port: port
    database: database
    // Azure Database for PostgreSQL flexible server requires TLS and this
    // Recipe does not override require_secure_transport.
    sslMode: 'required'
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    password: password
  }
}
