name: Test MongoDB Recipe

on:
  push:
    branches:
      - main
      - 21-add-k8s-mongodb-recipe-terraform
  pull_request:
    branches:
      - 21-add-k8s-mongodb-recipe-terraform

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      # Install kubectl and kind
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Create a local Kubernetes cluster
      - name: Create Kind Cluster
        run: kind create cluster --name tf-test

      # Apply Terraform
      - name: Terraform Init & Apply
        working-directory: recipes/kubernetes/mongodb
        run: |
          terraform init
          terraform apply \
            -var="name=test-mongodb" \
            -var="password=MySecretPass123" \
            -var="persistence=false" \
            -auto-approve

      # Optional: Test pods
      - name: List Pods
        run: kubectl get pods

      # Cleanup: Destroy Terraform resources
      - name: Terraform Destroy
        if: always()  # ensure it runs even if previous steps fail
        working-directory: recipes/kubernetes/mongodb
        run: |
          terraform destroy \
            -var="name=test-mongodb" \
            -var="password=MySecretPass123" \
            -var="persistence=false" \
            -auto-approve

      # Cleanup: Delete Kind cluster
      - name: Delete Kind Cluster
        if: always()
        run: kind delete cluster --name tf-test
